CREATE DATABASE MERCADO;

USE MERCADO;

CREATE TABLE TB_CLIENTES(
	CLIENTE_ID INT PRIMARY KEY AUTO_INCREMENT,
    CLI_NOME VARCHAR(100) NOT NULL,
    CLI_EMAIL VARCHAR(100) NOT NULL
);
CREATE TABLE TB_FORNECEDORES(
	FORN_ID INT PRIMARY KEY AUTO_INCREMENT,
    FORN_NOME VARCHAR(100) NOT NULL,
    FORN_CODIGO VARCHAR(10) NOT NULL,
    FORN_DESCRICAO VARCHAR(45) NOT NULL
);
CREATE TABLE TB_CATEGORIAS(
	CAT_ID INT PRIMARY KEY AUTO_INCREMENT,
	CAT_NOME VARCHAR(100) ,
    CAT_DESCRICAO VARCHAR(100),
    CAT_CODIGO VARCHAR(10)
);
CREATE TABLE TB_FUNCIONARIOS(
	FUNC_ID INT PRIMARY KEY AUTO_INCREMENT,
    FUNC_NOME VARCHAR(100),
    FUNC_CODIGO VARCHAR(12)
);

CREATE TABLE TB_COMPRAS(
	COMP_ID INT PRIMARY KEY AUTO_INCREMENT,
    COMP_DESCRICAO VARCHAR(100) NOT NULL,
    COMP_DATA DATETIME NOT NULL,
    COMP_VALOR DECIMAL NOT NULL ,
    CLIENTE_ID INT,
    FOREIGN KEY(CLIENTE_ID) REFERENCES TB_CLIENTES(CLIENTE_ID)
);
CREATE TABLE TB_VENDAS(
	VEND_ID INT PRIMARY KEY AUTO_INCREMENT,
    VEND_DESCRICAO VARCHAR(100) NOT NULL,
    VEND_DATA DATETIME NOT NULL,
    VEND_VALOR DECIMAL NOT NULL,
    FUNC_ID INT,
    FOREIGN KEY(FUNC_ID) REFERENCES TB_FUNCIONARIOS(FUNC_ID)
);

CREATE TABLE TB_PRODUTOS(
	PROD_ID INT PRIMARY KEY AUTO_INCREMENT,
    PROD_DESCRICAO VARCHAR(100) NOT NULL,
    PROD_VALOR DOUBLE NOT NULL,
    CAT_ID INT,
    FOREIGN KEY(CAT_ID) REFERENCES TB_CATEGORIAS(CAT_ID)
);

CREATE TABLE TB_VENDAS_PRODUTOS(
	VEND_ID INT,
    PROD_ID INT,
    VEND_PROD_QUANTIDADE INT NOT NULL,
    VEND_PROD_VALOR DECIMAL NOT NULL,
    FOREIGN KEY(VEND_ID) REFERENCES TB_VENDAS(VEND_ID),
    FOREIGN KEY(PROD_ID) REFERENCES TB_PRODUTOS(PROD_ID)
);

CREATE TABLE TB_PRODUTOS_COMPRAS(
	PROD_ID INT,
    COMP_ID INT,
    PROD_COMP_QUANTIDADE INT NOT NULL,
    PROD_COMP_VALOR DECIMAL NOT NULL,
    FOREIGN KEY(PROD_ID) REFERENCES TB_PRODUTOS(PROD_ID),
    FOREIGN KEY(COMP_ID) REFERENCES TB_COMPRAS(COMP_ID)
);

CREATE TABLE TB_PRODUTOS_FORNECEDORES(
	PROD_ID INT,
    FORN_ID INT,
    PROD_FORN_VALOR INT NOT NULL,
    FOREIGN KEY(PROD_ID) REFERENCES TB_PRODUTOS(PROD_ID),
    FOREIGN KEY(FORN_ID) REFERENCES TB_FORNECEDORES(FORN_ID)
);

